✨ Graphics api rework
BitCache-Labs/bx pull request #7
Opened 2024-07-28 13:17 UTC by JasondeWolff

Few things still need to be done in this PR (why it's a draft):
- [ ] Use new handle maps
- [ ] Revert my change of making sure BX_ASSERT evaluates in release mode

Things required after this PR is merged (not part of this imo):
 - Api unit tests
 - Fix faked opengl bindgroups (requires a shader include with some #define shader magic)

2024-07-31 13:30 UTC, ConorDamery requested changes
General notes:
- Make sure you include files with their full paths
- Make sure the CI is building before the final review
- All of graphics/toolkit don't belong in the engine lib

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/core/ecs.hpp
Can you explain why components need an UUID now?

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/core/macros.hpp
> +#define BX_ASSERT(condition, message) (condition)
Asserts and guards similar should not run on release, if you need the function (condition) to run split into multiple lines of code

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/core/resource.hpp
> +		//BX_LOGD("Resource ({}) increment ref count {}", handle, it->second.refCount);
Make sure to add the logs back before the final PR

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/core/resource.hpp
> +		//BX_LOGD("Resource ({}) decrement ref count {}", handle, it->second.refCount);
Make sure to add the logs back before the final PR

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/core/resource.hpp
> +		: m_handle(MakeHandle(filename)), m_uuid(GenUUID::MakeUUID())
Can you explain why resources need UUID now?

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/modules/graphics.hpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/modules/graphics/backend/graphics_opengl.hpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/modules/graphics/backend/graphics_vulkan.hpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/engine/modules/graphics/type.hpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/framework/resources/material.hpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on include/bx/framework/systems/renderer.hpp
Editor camera shouldn't exist here

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/editor/views/scene_view.cpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/engine/modules/graphics.cpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/engine/modules/script.cpp
> +	else if (s_error)
This check doesn't do anything

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/engine/modules/script.cpp
Note to self @ConorDamery : Help Jason with implementing the wren binding for new graphics api

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/engine/modules/window/backend/window_glfw.cpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/framework/resources/material.cpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/framework/resources/mesh.cpp
> +    vertexCreateInfo.name = Optional<String>::Some(Log::Format("{} Vertex Buffer", filename));
As discussed for strings optional doesn't make sense

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/framework/systems/renderer.cpp
Note to self @ConorDamery : Review this again once the final PR is finished

2024-07-31 13:30 UTC, ConorDamery commented on src/bx/runtime/editor_runtime.cpp
> +		// ImGuiImpl::EndFrame();
Why is this commented?

2024-07-31 13:44 UTC, JasondeWolff commented on include/bx/engine/containers/lazy_init.hpp
I feel like this is just a general programming pattern. It can be very useful outside of the graphics module and doesn't necessarily have anything to do with it.

2024-07-31 13:47 UTC, JasondeWolff commented on include/bx/engine/core/ecs.hpp
This way the renderer can internally track which components are unique, required to have a bone buffer for every animator component for example (which is ofc cached over multiple frames and not recreated every frame). Creating this bone buffer shouldn't be inside the animator component like how it was before, as this can differ renderer to renderer. E.g. maybe all bones should be together in one giant bone buffer instead of split up per animator.

2024-07-31 13:50 UTC, JasondeWolff commented on src/bx/runtime/editor_runtime.cpp
> +		// ImGuiImpl::EndFrame();
I'll remove the comment all together later, `ImGui::EndFrame()` is now called inside the renderer `EndFrame()` as the renderer needs control over when this happens. For vulkan for example it must be during the backends rendering process, injecting it afterwards is not possible.

2024-07-31 13:52 UTC, JasondeWolff commented on include/bx/engine/core/resource.hpp
> +		: m_handle(MakeHandle(filename)), m_uuid(GenUUID::MakeUUID())
Bit as the same story as for components, the renderer requires to keep track of unique shader resources. It generates graphics pipelines for new shader resources and caches them over multiple frames. Ofc making the shader resource hashable also works but that's way slower for performance.

2024-07-31 13:57 UTC, JasondeWolff commented on src/bx/engine/modules/script.cpp
> +	else if (s_error)
the 3 lines below it make sure the engine fails, seemed convenient at the time, can remove if undesired

2024-07-31 14:13 UTC, ConorDamery commented on include/bx/engine/containers/lazy_init.hpp
Yeah you are correct that it is a pattern so it wouldn't really belong in the containers folder, but also it's a pattern that encourages bad behaviour, especially for the graphics side which is used in explicit control of when something is initialized makes the code faster and less error prone. Whilst it has some advantages as a pattern they are seldom and I'd argue it's more often an anti-pattern. I don't believe it should be part of the core lib, and I don't encourage it's use but if you really must use it you can have it on the backend side

2024-07-31 14:18 UTC, ConorDamery commented on include/bx/engine/core/ecs.hpp
So every component is unique, there should never be shared data between components and especially not having a component be part of multiple entities. But yeah if it's for the optimization of the bone matrices then I think the renderer should handle the data sharing part, and also the updating so if there's already a "pose" shared multiple times that it can update the entire thing and be done with it.

2024-07-31 14:19 UTC, ConorDamery commented on include/bx/engine/core/resource.hpp
> +		: m_handle(MakeHandle(filename)), m_uuid(GenUUID::MakeUUID())
Yeah I think it makes sense for the resource to have a unique ID, but there was already a hash ID for that purpose?

2024-07-31 14:21 UTC, ConorDamery commented on include/bx/framework/systems/renderer.hpp
Hmm I still don't want editor code in code that is general for the engine. Why can't the renderer simply have an API the editor can use instead of injecting editor code into it?

2024-07-31 14:22 UTC, ConorDamery commented on src/bx/engine/modules/script.cpp
> +	else if (s_error)
Well the whole point of the scripting is that we don't want it to crash, so I'd rather not have a code path that literally makes it crash :)

2024-07-31 14:24 UTC, ConorDamery commented on src/bx/runtime/editor_runtime.cpp
> +		// ImGuiImpl::EndFrame();
Ok, let's leave this for the meeting then, there should be a way to have imgui be independent, that was the original goal of making it a module, but I can understand that the dependency of the window and graphics can be problematic

2024-08-01 06:59 UTC, JasondeWolff commented on include/bx/engine/containers/lazy_init.hpp
I'll move it inside the graphics folder

2024-08-01 07:35 UTC, JasondeWolff commented on include/bx/engine/core/resource.hpp
> +		: m_handle(MakeHandle(filename)), m_uuid(GenUUID::MakeUUID())
You're right, removed UUID in favor of using the ResourceHandle directly.

2024-08-01 07:36 UTC, JasondeWolff commented on include/bx/engine/core/ecs.hpp
Reverted the change, `Animator` now holds it's own bones buffer (like before). I don't see this working with all renderers but as `Animator` itself is part of the framework (and meant to be modifiable) I think it's fine.

2024-08-01 19:50 UTC, merged